### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by markrey** [telefonicaid/lwm2m-node-lib#100]
Hi,

It's amazing work done for Node-Lib. I am trying to use the same and might be able to give some issues and fixes on registration later. 
I couldn't find open-source license file for the project. Would it be possible to add the same ?
I would recommend something of Apache or MIT if possible. ( Which gives flexibility to distribute )

Thank you.

**Comment by muoren** [comment]
@markrey  it uses The GNU Affero General Public License 3.0, see the code.
