### ISSUE TITLE
Problem registring devices in MongoDB

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/lwm2m-node-lib#131]
Doing some tests, I have found problems during the registry of new devices using MongoDB.

After some research, I think that they are related to https://github.com/telefonicaid/lwm2m-node-lib/pull/129.

To illustrate them, I have opened a new PR in https://github.com/telefonicaid/lwm2m-node-lib/pull/130

You can see in the first commit https://github.com/telefonicaid/lwm2m-node-lib/pull/130/commits/f5fab6fe7d3bf93c3eac60a16947526ddbd332fb, which only adds some additional checking in one of the unit tests, that an appropriate `id` is not returned.

After downgrading Mongoose version in https://github.com/telefonicaid/lwm2m-node-lib/pull/130/commits/c8427a895af61351d2877f7c69a1f7f1252dc125, all tests are passed.

@AlvaroVega @fgalan

**Comment by fgalan** [comment]
Fixed by PR #130
