### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by dcalvoalonso** [telefonicaid/lwm2m-node-lib#134]
Dependencies in https://github.com/telefonicaid/lwm2m-node-lib/blob/master/package.json should be reviewed and updated.

For instance: https://www.npmjs.com/package/mongoose-auto-increment, is not maintained currently. Interoperability with previous versions should be preserved if possible or at least providing a tool or mechanism to do the upgrade.

**Comment by fgalan** [comment]
Fixed by PR #136

**Comment by dcalvoalonso** [comment]
After the merge of #136, we can close this issue.
