### ISSUE TITLE
Remove Node v4

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/lwm2m-node-lib#137]
(To be addresses in January 2019)

Node v4 will be removed by the end of 2018. In particular, this issue involves the following actions:

* Node v4 should be removed from .travis.yml
* engine version should be modified to be >=6 in packages.json
* logops library should be updated to 2.1.0 in packages.json

**Comment by fgalan** [comment]
Fixed by PR #136

**Comment by dcalvoalonso** [comment]
Shall be close this issue?

**Comment by fgalan** [comment]
I think so. Nothing else is pending regarding v4 removal, isn't it? Closing.
