### ISSUE TITLE
Contribution guidelines not aligned with project branching model

### ISSUE THREAD

**Issue by versatildefuy** [telefonicaid/lwm2m-node-lib#149]
Problem:
I tried to follow the contribution guideline but I found the branching model described in `docs/contribution.md`. There is no develop branch in this repo. Besides, the contribution file refers to the repo as lightweightm2m-iotagent while the repo is called lwm2m-node-lib.

Could you update this contribution guide?

Thank you in advance,

**Comment by fgalan** [comment]
Thanks for make us aware of this!

PR https://github.com/telefonicaid/lwm2m-node-lib/pull/151 implements the fixes on contributions.md.
