### ISSUE TITLE
device IP change

### ISSUE THREAD

**Issue by ai-Lemon** [telefonicaid/lwm2m-node-lib#161]
The server was unable to update the device IP change in time, resulting in the device timeout problem when sending data.
error:     Code: CLIENT_CONNECTION_ERROR
Message: There was an error sending a request to the client: Error: No reply in 247s

**Comment by fgalan** [comment]
Could you provide more detail on how to reproduce the issue, please? I mean, a detailed description of steps from the beginning to reach the issue you mention. That would be useful to analyze and debug. Thanks!

**Comment by ai-Lemon** [comment]
我使用的lwm2m客户端是NB-iot设备，连接经过一段时间后，设备的ip或端口会产生变化，而服务器存储的设备信息为旧信息，所以导致服务器写数据至设备不成功。所以我希望的是能不能在接收会话的时候服务器能不能重新更新设备的地址等信息。
The lwm2m client I use is a NB IOT device. After a period of connection, the IP or port of the device will change, and the device information stored by the server is old information, so the server fails to write data to the device. So what I hope is whether the server can update the address and other information of the device when receiving the session.Thanks!

**Comment by ai-Lemon** [comment]
The lwm2m client I use is a NB-iot device. After a period of time, the IP or port of the device will change, and the equipment information stored by the server is old information, so the server will not write data to the device successfully. So what I hope is whether the server can update the address and other information of the device when receiving the session.Thanks!

**Comment by ai-Lemon** [comment]
I wonder if the server can solve this problem by turning on queue mode.

**Comment by fgalan** [comment]
The issue has been closed. Shoud we understand that you finally solved the issue and the issue? In that case, could you share with the community how did you solve it, to helps others with a similar problem, please? Thanks!
