### ISSUE TITLE
Handle 404 response client on registration info  update

### ISSUE THREAD

**Issue by kudla** [telefonicaid/lwm2m-node-lib#38]
Since lwm2m server is reloaded it has no more information about clients registered ealier.
In this case update request returns code 4.04.
Can we handle this as an error in callback;
https://github.com/telefonicaid/lwm2m-node-lib/blob/develop/lib/lwm2m-client.js#L270
```
    req.on('response', function(res) {
        logger.debug(context, 'Update registration response code:\n%s', res.code);
        if (res.code === '4.04') {
            callback(new errors.DeviceNotFound(deviceInformation.location));
            return;
        }

        callback(null, deviceInformation);
    });
```

**Comment by dmoranj** [comment]
Yes, we should. We need to revise the error conditions in multiple scenarios. I'll try to add a test case to cover it.

**Comment by dmoranj** [comment]
Should be working by now (Mongo DB information was being erased at start, maybe as a result of some tests). Also, make sure you `start` the server on server reload.
