### ISSUE TITLE
Add Travis CI for the Project

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/lwm2m-node-lib#55]
Currently, the tests and linters must be executed manually from the local environment. They should be checked in Travis in order to automatically check the PRs.

**Comment by fgalan** [comment]
What about the same for Perseo FE?

**Comment by dmoranj** [comment]
Ok. Once its working here I'll start to add it both for PEP and CEP.

**Comment by dmoranj** [comment]
Done.
